spring:
  application:
    name: transactions-api
  datasource:
    url: jdbc:postgresql://localhost:5432/transactions-db
    username: <your-user-here>
    password: <your-password-here>
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: always
